src/Entity/Administrateurs.php
<?php

/**
 * Auteur : Johan
 */

namespace App\Entity;

use App\Repository\AdministrateursRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=AdministrateursRepository::class)
 */
class Administrateurs
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $prenom;

    /**
     * @ORM\Column(type="date")
     */
    private $date_naissance;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adresse;

    /**
     * @ORM\Column(type="integer")
     */
    private $code_postale;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $ville;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $telephone;

    /**
     * @ORM\OneToOne(targetEntity=User::class, inversedBy="administrateurs", cascade={"persist", "remove"})
     */
    private $user;

	public function __construct()
	{
		// Initialisation du propriété user pour la création automatique d'un compte pour l'employé
		$this->setUser(new User);
	}

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getDateNaissance(): ?\DateTimeInterface
    {
        return $this->date_naissance;
    }

    public function setDateNaissance(\DateTimeInterface $date_naissance): self
    {
        $this->date_naissance = $date_naissance;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getCodePostale(): ?int
    {
        return $this->code_postale;
    }

    public function setCodePostale(int $code_postale): self
    {
        $this->code_postale = $code_postale;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(string $ville): self
    {
        $this->ville = $ville;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(string $telephone): self
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

	// Création de l'utilisateur associé è l'employé
	public function setUserOnCreateAdmin(string $email, string $password): self
	{
		// Ajout du role
		$this->user->setRoles(['ROLE_EMPLOYEE']);

		// Assignement des identifiants
		$this->user->setEmail($email);
		$this->user->setPassword($password);

		return $this;
	}
}

src/Controller/AdministrateursController.php
<?php

namespace App\Controller;

use App\Entity\Administrateurs;
use App\Entity\User;
use App\Form\AdminsType;
use Doctrine\DBAL\Exception\ForeignKeyConstraintViolationException;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Security;

#[Route('/administrateurs', name: 'administrateurs_')]
class AdministrateursController extends AbstractController
{
	// Initialisation des attributs de classe
	public function __construct(Security $security)
	{
		$this->security = $security;
		// $this->user est l'utilisateur authentifié sur l'application
		$this->user = $this->security->getUser();
	}

	#[Route('/', name: 'index')]
	public function index(ManagerRegistry $doctrine): Response
	{
		$admins = $doctrine->getRepository(Administrateurs::class)->findAll();
		return $this->render('administrateurs/index.html.twig', compact('admins'));
	}

	// Formulaire pour ajouter un nouveau employé
	#[Route('/new', name: 'new', methods: ['GET', 'POST'])]
	public function new(Request $request, EntityManagerInterface $entityManager, UserPasswordHasherInterface $userPasswordHasher): Response
	{
		$admin = new Administrateurs();
		$form = $this->createForm(AdminsType::class, $admin);
		$form->handleRequest($request);

		if ($form->isSubmitted() && $form->isValid()) {
			// Création d'un utilisateur relatif au employé
			$admin->setUserOnCreateAdmin(
				$form->get('email')->getData(),
				// Cryptage le mot de passe du employé
				$userPasswordHasher->hashPassword(
					new User,
					$form->get('password')->getData()
				)
			);

			$entityManager->persist($admin);
			$entityManager->flush();

			return $this->redirectToRoute('administrateurs_index');
		}

		return $this->render('administrateurs/new.html.twig', [
			'admin' => $admin,
			'form' => $form->createView(),
		]);
	}

	// Affichage d'un employé
	#[Route('/{id}', name: 'show', methods: ['GET'])]
	public function show(Administrateurs $admin): Response
	{
		return $this->render('administrateurs/show.html.twig', [
			'admin' => $admin,
		]);
	}

	// Modification d'un employé
	#[Route('/{id}/edit', name: 'edit', methods: ['GET', 'POST'])]
	public function edit(Request $request, Administrateurs $admin, EntityManagerInterface $entityManager, UserPasswordHasherInterface $userPasswordHasher): Response
	{
		$form = $this->createForm(AdminsType::class, $admin);
		$form->handleRequest($request);

		if ($form->isSubmitted() && $form->isValid()) {
			// Modification des identifiants du employé
			$admin->setUserOnCreateAdmin(
				$form->get('email')->getData(),
				// Cryptage le mot de passe du employé
				$userPasswordHasher->hashPassword(
					new User,
					$form->get('password')->getData()
				)
			);

			$entityManager->flush();

			return $this->redirectToRoute('administrateurs_index');
		}

		return $this->render('administrateurs/edit.html.twig', [
			'admin' => $admin,
			'form' => $form->createView(),
		]);
	}

	// Suppression d'un employé
	#[Route('/{id}', name: 'delete', methods: ['POST', 'DELETE'])]
	public function delete(Request $request, Administrateurs $admin, EntityManagerInterface $entityManager): Response
	{
		// Verification de la validité du jeton de l'utilisateur connecté
		if ($this->isCsrfTokenValid('delete' . $admin->getId(), $request->request->get('_token'))) {
			$entityManager->remove($admin);
			$entityManager->flush();
		}

		// Redirection vers la liste des employés
		return $this->redirectToRoute('administrateurs_index');
	}
}

templates/administrateurs/_delete_button.html.twig
<form method="post" action="{{ path('administrateurs_delete', {'id': admin.id}) }}"
	onsubmit="return confirm('Etes-vous sur de vouloir supprimer cet administrateur ?');" style="display: contents;">
	<input type="hidden" name="_method" value="DELETE">
	<input type="hidden" name="_token" value="{{ csrf_token('delete' ~ admin.id) }}">
	<button class="btn btn-danger btn-sm delete-btn"><i class="fas fa-trash"></i></button>
</form>

templates/administrateurs/_delete_form.html.twig
<form style="display: contents;" method="post" action="{{ path('administrateurs_delete', {'id': admin.id}) }}" onsubmit="return confirm('Etes-vous sur de vouloir supprimer cet administrateur?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ admin.id) }}">
    <button class="btn btn-danger btn-sm"><i class="fas fa-trash"></i> Supprimer</button>
</form>

templates/administrateurs/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    	<button class="btn btn-secondary btn-sm"><i class="fas fa-edit"></i> {{ button_label|default('Enregistrer') }}</button>
{{ form_end(form) }}

templates/administrateurs/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier l'employé{% endblock %}

{% block body %}
<a class="btn btn-primary btn-sm" href="{{ path('administrateurs_index') }}"><i class="fas fa-arrow-left"></i> Revenir à la liste</a>
<hr>
<div class="float-end">
	{{ include('administrateurs/_delete_form.html.twig') }}
</div>
<h3>Modifier le client</h3>
{% if app.user.isEmployee() %}


{% endif %}
<div class="border p-3">
	{{ include('administrateurs/_form.html.twig', {'button_label': 'Modifier'}) }}
</div>

{% endblock %}

templates/administrateurs/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Clients index{% endblock %}

{% block body %}
{% for message in app.flashes('message') %}
<div class="alert alert-danger text-center">
	{{ message }}
</div>
{% endfor %}

<h3>Liste des employés</h3>
<hr>
<a class="btn btn-success float-end" href="{{ path('administrateurs_new') }}"><i class="fas fa-plus"></i> Ajouter un employé</a>

<table class="table table-striped table-hover">
	<thead>
		<tr>
			<th>ID</th>
			<th>Nom</th>
			<th>Prenom</th>
			<th>Naissance</th>
			<th>Code postale</th>
			<th>Ville</th>
			<th>Telephone</th>
			<th class="text-center">-</th>
		</tr>
	</thead>
	<tbody>
		{% for admin in admins %}
		<tr>
			<td class="fw-bold">{{ admin.id }}</td>
			<td>{{ admin.nom }}</td>
			<td>{{ admin.prenom }}</td>
			<td>{{ admin.dateNaissance ? admin.dateNaissance|date('Y-m-d') : '' }}</td>
			<td>{{ admin.codePostale }}</td>
			<td>{{ admin.ville }}</td>
			<td>{{ admin.telephone }}</td>
			<td class="text-center">
				<div class="btn-group" role="group" aria-label="Basic example">
					<a href="{{ path('administrateurs_show', {'id': admin.id}) }}"><button type="button"
							class="btn btn-primary btn-sm show-btn"><i class="fas fa-eye"></i></button></a>
					<a href="{{ path('administrateurs_edit', {'id': admin.id}) }}"><button type="button"
							class="btn btn-secondary btn-sm edit-btn"><i class="fas fa-edit"></i></button></a>
					{% include "administrateurs/_delete_button.html.twig" %}
				</div>
			</td>
		</tr>
		{% else %}
		<tr>
			<td colspan="10">Aucun résultat</td>
		</tr>
		{% endfor %}
	</tbody>
</table>

{% endblock %}

templates/administrateurs/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouvel employé{% endblock %}

{% block body %}
<a class="btn btn-primary btn-sm" href="{{ path('administrateurs_index') }}"><i class="fas fa-arrow-left"></i> Revenir à la
	liste</a>
<hr>
<h3>Ajouter un employé</h3>
<div class="border p-3">
	{{ include('administrateurs/_form.html.twig') }}
</div>

{% endblock %}

templates/administrateurs/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Administrateurs{% endblock %}

{% block body %}
{% if app.user.isEmployee() %}
<a class="btn btn-primary btn-sm" href="{{ path('administrateurs_index') }}"><i class="fas fa-arrow-left"></i> Revenir à la
	liste</a>
<hr>
<h3>Détails de l'employé</h3>
{% endif %}

<div class="card mb-4 w-50">
	<div class="card-body bg-dark text-white">
		<h5 class="card-title">{{admin.prenom}} {{admin.nom| upper}}</h5>
	</div>
	<ul class="list-group list-group-flush">
		<li class="list-group-item">Naissance: {{ admin.dateNaissance ? admin.dateNaissance|date('l d F Y') : '' }}
		</li>
		<li class="list-group-item">Adresse: {{admin.adresse}}</li>
		<li class="list-group-item">Code postale: {{ admin.codePostale }}</li>
		<li class="list-group-item">Ville: {{ admin.ville }}</li>
		<li class="list-group-item">Télephone: {{ admin.telephone }}</li>
		<li class="list-group-item">Email: {{ admin.user.email }}</li>
	</ul>
	{% if app.user.isEmployee() %}
	<div class="card-body">
		<a class="btn btn-secondary btn-sm" href="{{ path('administrateurs_edit', {'id': admin.id}) }}"><i
				class="fas fa-edit"""></i> Modifier</a>
		{{ include('administrateurs/_delete_form.html.twig') }}


	</div>
	{% endif %}
</div>



{% endblock %}